FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

COPY consumer.py .
COPY consumer_team.py .
COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y python3-pip libgl1-mesa-glx libglib2.0-0 && \
    pip3 install --no-cache-dir -r requirements.txt

CMD ["python3", "consumer.py"]
