FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

COPY producer.py .
COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --no-cache-dir -r requirements.txt && \
    ln -s /usr/bin/python3 /usr/bin/python

CMD ["python3", "producer.py"]
